# Generated by Django 2.2.10 on 2022-02-02 09:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20220202_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Subtitle')),
                ('content', ckeditor.fields.RichTextField(max_length=120, verbose_name='Content')),
                ('image', models.ImageField(default='null', upload_to='tvshows', verbose_name='Image')),
                ('public', models.BooleanField(verbose_name='Public?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited at')),
                ('categories', models.ManyToManyField(blank=True, to='blog.Category', verbose_name='Categories')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tv Show',
                'verbose_name_plural': 'Tv Shows',
            },
        ),
    ]
