# Generated by Django 2.2.10 on 2022-02-03 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tvshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Content'),
        ),
    ]
